[libraries]
junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
r8 = "com.android.tools:r8:8.7.18"
kotlin-gradle-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
